trigger: none

variables:
  - name: "PoolName"
    value: "ubuntu-latest"
  - group: general

stages:
  - stage: Staging
    displayName: "Deploy Staging Infrastructure"
    jobs:
      - template: templates/stages/jobs/run-pulumi.yaml
        parameters:
          poolName: $(PoolName)
          subscription: $(subscription)
          environmentName: "staging"
    
  - stage: Production
    displayName: "Deploy Production Infrastructure"
    dependsOn: Staging
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'Manual'))
    jobs:
      - template: templates/stages/jobs/run-pulumi.yaml
        parameters:
          poolName: $(PoolName)
          subscription: $(subscription)
          environmentName: "production"
