trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure

variables:
  - group: general

stages:
  - stage: Infrastructure
    displayName: "Update infrastructure"
    jobs:
      - job: Pulumi
        displayName: "Run Pulumi"
        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: Pulumi@1
            displayName: "Get config"
            inputs:
              azureSubscription: 'BizSpark'
              command: 'config'
              args: 'refresh'
              cwd: 'infrastructure'
              stack: 'staging'

          - task: Pulumi@1
            displayName: "Preview Pulumi"
            inputs:
              azureSubscription: $(subscription)
              command: "preview"
              cwd: "infrastructure"
              stack: "staging"

          - task: Pulumi@1
            displayName: "Run Pulumi"
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            inputs:
              azureSubscription: $(subscription)
              command: "up"
              args: "--yes"
              cwd: "infrastructure"
              stack: "staging"
