trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure

variables:
  - group: general

stages:
  - stage: Infrastructure
    displayName: "Update infrastructure"
    jobs:
      - job: Pulumi
        displayName: "Run Pulumi"
        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: UseDotNet@2
            displayName: Use .NET 6.0
            inputs:
              packageType: 'sdk'
              version: '5.0.x'

          - task: Pulumi@1
            inputs:
              azureSubscription: $(subscription)
              command: "up"
              args: "--yes"
              cwd: "infrastructure"
              stack: "staging"
              createStack: true
